### ISSUE TITLE
is the plugin useable?

### ISSUE THREAD

**Issue by crackedbeefcake** [amerlyq/nou.vim#1]
hi,
i stumbled upon this repo by chance, is it ready for use?

**Comment by amerlyq** [comment]
I don't really know what you mean by "usable". But I use it every day as
org-mode through more than year. Check my other repos for files with .nou
extension to get gist of it.

Sorry, if you think it's something more, than it actually is :)
It's somewhat incomplete and somewhat broken - like requiring nvim and
terminal with true color support, but I never had much energy to fix it.

**Comment by actionless** [comment]
i think some brief Syntax Guide documentation would be useful

or in case of full support of orgmode syntax -- some mention of that

**Comment by amerlyq** [comment]
Sorry, no full or any significant support for orgmode planned and definitely I have no intention to provide compatible syntax :)

I'm focused on different set of features -- annotated decision making, titled web links hierarchy and light shell code examples, plus simple todo lists for weekly planning, which of course are implemented in org-mode but not to my taste.
You can see many examples of actually written docs in https://github.com/amerlyq/airy

And... very brief syntax guide is already present in `doc/nou-markup.txt`, which will have much more sense if you open it with https://github.com/amerlyq/nou.vim installed to see actual colors. It's not exhaustive but acceptable.
As for 100+ highlighted keywords enumerated at https://github.com/amerlyq/aeternum/blob/master/documenting/fmt/notches.nou -- you can install plugin https://github.com/amerlyq/airy/blob/master/vim/plugin/everywhere-notches.vim to highlight them everywhere (I still haven't decided if it needs separate repo).

In any case, I really appreciate any snippet of documentation/code you can contribute -- if you find examples above personally appealing and useful. Or instead show some workflow useful for you and which I could also integrate in my daily life -- so I myself would be motivated to work on additional features.

Despite having rather long `TODO.nou` list here full of ideas and musings I had little to no time to invest into further enhancement after minimal set of personally required features was implemented for my typical workflows with notes. After all I myself can't compare with whole `org-mode` community :)

**Comment by actionless** [comment]
> https://github.com/amerlyq/nou.vim/blob/master/doc/nou-markup.txt

yeah, that's what i was looking for, thanks!

i think it would be useful to link it from the README.md
